from bson.objectid import ObjectId

### get_job_dictionary_as_list ###
get_job_dictionary_as_list_test_variables = {}
get_job_dictionary_as_list_test_variables['parent_job_information'] = \
    [{'_id': ObjectId('5cababe94960065c9eb02488'),
      'creationDate': '2019-04-08 16:15:37',
      'jacs_id': ['2653066155381194769'],
      'jobName': 'Job_0.35.0_2019-04-08_16:08:00_vm638.int.janelia.org',
      'remainingStepNames': ['clusterPT',
                             'llsCreateTileConfigurationFiles',
                             'c3dReformat',
                             'regiprepReformat',
                             'clusterMF',
                             'llsConvertTilesToN5',
                             'regiprepImages',
                             'localAP',
                             'llsFlatfieldCorrection',
                             'antsRigidAffineRegistration',
                             'antsDeformableRegistration',
                             'clusterTF',
                             'antsWarpAffine',
                             'llsIgorDeconvolution',
                             'localEC',
                             'llsStitching',
                             'antsWarpAffineAndDeformable',
                             'clusterCS',
                             'llsExportToN5',
                             'regiprepLabels',
                             'clusterFR',
                             'llsConvertN5ExportToSliceTIFF'],
      'state': 'ERROR',
      'stepOrTemplateName': 'Template: Building Test Json',
      'steps': [{'name': 'aicSimviewSingleCameraGlobalParameters', 'state': 'NOT YET QUEUED'},
                {'name': 'clusterPT', 'pause': 0, 'state': 'ERROR'},
                {'name': 'llsCreateTileConfigurationFiles', 'pause': 0, 'state': 'NOT YET QUEUED'},
                {'name': 'c3dReformat', 'pause': 0, 'state': 'NOT YET QUEUED'},
                {'name': 'regiprepReformat', 'pause': 0, 'state': 'NOT YET QUEUED'},
                {'name': 'clusterMF', 'pause': 0, 'state': 'NOT YET QUEUED'},
                {'name': 'llsConvertTilesToN5', 'pause': 0, 'state': 'NOT YET QUEUED'},
                {'name': 'regiprepImages', 'pause': 0, 'state': 'NOT YET QUEUED'},
                {'name': 'localAP', 'pause': 0, 'state': 'NOT YET QUEUED'},
                {'name': 'llsFlatfieldCorrection', 'pause': 0, 'state': 'NOT YET QUEUED'},
                {'name': 'antsRigidAffineRegistration', 'pause': 0, 'state': 'NOT YET QUEUED'},
                {'name': 'antsDeformableRegistration', 'pause': 0, 'state': 'NOT YET QUEUED'},
                {'name': 'clusterTF', 'pause': 0, 'state': 'NOT YET QUEUED'},
                {'name': 'antsWarpAffine', 'pause': 0, 'state': 'NOT YET QUEUED'},
                {'name': 'llsIgorDeconvolution', 'pause': 0, 'state': 'NOT YET QUEUED'},
                {'name': 'localEC', 'pause': 0, 'state': 'NOT YET QUEUED'},
                {'name': 'llsStitching', 'pause': 0, 'state': 'NOT YET QUEUED'},
                {'name': 'antsWarpAffineAndDeformable', 'pause': 0, 'state': 'NOT YET QUEUED'},
                {'name': 'clusterCS', 'pause': 0, 'state': 'NOT YET QUEUED'},
                {'name': 'llsExportToN5', 'pause': 0, 'state': 'NOT YET QUEUED'},
                {'name': 'regiprepLabels', 'pause': 0, 'state': 'NOT YET QUEUED'},
                {'name': 'clusterFR', 'pause': 0, 'state': 'NOT YET QUEUED'},
                {'name': 'llsConvertN5ExportToSliceTIFF', 'pause': 0, 'state': 'NOT YET QUEUED'}],
      'submissionAddress': None}]

get_job_dictionary_as_list_test_variables['list_to_return'] = \
    [{'creationDate': '2019-04-08 16:15:37',
      'id': '5cababe94960065c9eb02488',
      'jacs_id': ['2653066155381194769'],
      'jobName': 'Job_0.35.0_2019-04-08_16:08:00_vm638.int.janelia.org',
      'jobType': 'Template: Building Test Json',
      'selectedSteps': {
          'names': 'clusterPT,llsCreateTileConfigurationFiles,c3dReformat,regiprepReformat,clusterMF,llsConvertTilesToN5,regiprepImages,localAP,llsFlatfieldCorrection,antsRigidAffineRegistration,antsDeformableRegistration,clusterTF,antsWarpAffine,llsIgorDeconvolution,localEC,llsStitching,antsWarpAffineAndDeformable,clusterCS,llsExportToN5,regiprepLabels,clusterFR,llsConvertN5ExportToSliceTIFF',
          'states': 'ERROR,RESET,NOT YET QUEUED,NOT YET QUEUED,NOT '
                    'YET QUEUED,NOT YET QUEUED,NOT YET QUEUED,NOT YET '
                    'QUEUED,NOT YET QUEUED,NOT YET QUEUED,NOT YET '
                    'QUEUED,NOT YET QUEUED,NOT YET QUEUED,NOT YET '
                    'QUEUED,NOT YET QUEUED,NOT YET QUEUED,NOT YET '
                    'QUEUED,NOT YET QUEUED,NOT YET QUEUED,NOT YET '
                    'QUEUED,NOT YET QUEUED,NOT YET QUEUED,NOT YET '
                    'QUEUED',
          'submissionAddress': ''},
      'state': 'ERROR',
      'stepOrTemplateName': '/workflow?template=Building+Test+Json',
      'submissionAddress': ''}]

### add_fields_to_job_information_from_db ###
add_fields_to_job_information_from_db_test_variables = {}
add_fields_to_job_information_from_db_test_variables['child'] = {}
add_fields_to_job_information_from_db_test_variables['child']['parent_or_child'] = 'child'
add_fields_to_job_information_from_db_test_variables['child']['job_information_from_db'] = \
    {'_id': ObjectId('5cababe94960065c9eb02488'),
     'remainingStepNames': ['clusterPT',
                            'llsCreateTileConfigurationFiles',
                            'c3dReformat',
                            'regiprepReformat',
                            'clusterMF',
                            'llsConvertTilesToN5',
                            'regiprepImages',
                            'localAP',
                            'llsFlatfieldCorrection',
                            'antsRigidAffineRegistration',
                            'antsDeformableRegistration',
                            'clusterTF',
                            'antsWarpAffine',
                            'llsIgorDeconvolution',
                            'localEC',
                            'llsStitching',
                            'antsWarpAffineAndDeformable',
                            'clusterCS',
                            'llsExportToN5',
                            'regiprepLabels',
                            'clusterFR',
                            'llsConvertN5ExportToSliceTIFF'],
     'stepOrTemplateName': 'Template: Building Test Json',
     'steps': [{'name': 'aicSimviewSingleCameraGlobalParameters',
                'state': 'NOT YET QUEUED'},
               {'_id': '2653066155381198865',
                'creationTime': '2019-04-08 16:15:41',
                'elapsedTime': '0:01:43',
                'endTime': '2019-04-08 16:17:24',
                'name': 'clusterPT',
                'pause': 0,
                'state': 'ERROR'},
               {'name': 'llsCreateTileConfigurationFiles',
                'pause': 0,
                'state': 'NOT YET QUEUED'},
               {'name': 'c3dReformat', 'pause': 0, 'state': 'NOT YET QUEUED'},
               {'name': 'regiprepReformat', 'pause': 0, 'state': 'NOT YET QUEUED'},
               {'name': 'clusterMF', 'pause': 0, 'state': 'NOT YET QUEUED'},
               {'name': 'llsConvertTilesToN5',
                'pause': 0,
                'state': 'NOT YET QUEUED'},
               {'name': 'regiprepImages', 'pause': 0, 'state': 'NOT YET QUEUED'},
               {'name': 'localAP', 'pause': 0, 'state': 'NOT YET QUEUED'},
               {'name': 'llsFlatfieldCorrection',
                'pause': 0,
                'state': 'NOT YET QUEUED'},
               {'name': 'antsRigidAffineRegistration',
                'pause': 0,
                'state': 'NOT YET QUEUED'},
               {'name': 'antsDeformableRegistration',
                'pause': 0,
                'state': 'NOT YET QUEUED'},
               {'name': 'clusterTF', 'pause': 0, 'state': 'NOT YET QUEUED'},
               {'name': 'antsWarpAffine', 'pause': 0, 'state': 'NOT YET QUEUED'},
               {'name': 'llsIgorDeconvolution',
                'pause': 0,
                'state': 'NOT YET QUEUED'},
               {'name': 'localEC', 'pause': 0, 'state': 'NOT YET QUEUED'},
               {'name': 'llsStitching', 'pause': 0, 'state': 'NOT YET QUEUED'},
               {'name': 'antsWarpAffineAndDeformable',
                'pause': 0,
                'state': 'NOT YET QUEUED'},
               {'name': 'clusterCS', 'pause': 0, 'state': 'NOT YET QUEUED'},
               {'name': 'llsExportToN5', 'pause': 0, 'state': 'NOT YET QUEUED'},
               {'name': 'regiprepLabels', 'pause': 0, 'state': 'NOT YET QUEUED'},
               {'name': 'clusterFR', 'pause': 0, 'state': 'NOT YET QUEUED'},
               {'name': 'llsConvertN5ExportToSliceTIFF',
                'pause': 0,
                'state': 'NOT YET QUEUED'}]}

add_fields_to_job_information_from_db_test_variables['child']['step_or_template_name'] = 'Template: Building Test Json'
add_fields_to_job_information_from_db_test_variables['child']['step_or_template_name_path'] = '/workflow?template=Building+Test+Json'
add_fields_to_job_information_from_db_test_variables['child']['child_job_info'] = \
    [{'_id': '2653066155381198865',
      'creationTime': '2019-04-08 16:15:41',
      'elapsedTime': '0:01:43',
      'endTime': '2019-04-08 16:17:24',
      'name': 'clusterPT',
      'pause': 0,
      'state': 'ERROR'},
     {'name': 'llsCreateTileConfigurationFiles',
      'pause': 0,
      'state': 'NOT YET QUEUED'},
     {'name': 'c3dReformat', 'pause': 0, 'state': 'NOT YET QUEUED'},
     {'name': 'regiprepReformat', 'pause': 0, 'state': 'NOT YET QUEUED'},
     {'name': 'clusterMF', 'pause': 0, 'state': 'NOT YET QUEUED'},
     {'name': 'llsConvertTilesToN5', 'pause': 0, 'state': 'NOT YET QUEUED'},
     {'name': 'regiprepImages', 'pause': 0, 'state': 'NOT YET QUEUED'},
     {'name': 'localAP', 'pause': 0, 'state': 'NOT YET QUEUED'},
     {'name': 'llsFlatfieldCorrection', 'pause': 0, 'state': 'NOT YET QUEUED'},
     {'name': 'antsRigidAffineRegistration', 'pause': 0, 'state': 'NOT YET QUEUED'},
     {'name': 'antsDeformableRegistration', 'pause': 0, 'state': 'NOT YET QUEUED'},
     {'name': 'clusterTF', 'pause': 0, 'state': 'NOT YET QUEUED'},
     {'name': 'antsWarpAffine', 'pause': 0, 'state': 'NOT YET QUEUED'},
     {'name': 'llsIgorDeconvolution', 'pause': 0, 'state': 'NOT YET QUEUED'},
     {'name': 'localEC', 'pause': 0, 'state': 'NOT YET QUEUED'},
     {'name': 'llsStitching', 'pause': 0, 'state': 'NOT YET QUEUED'},
     {'name': 'antsWarpAffineAndDeformable', 'pause': 0, 'state': 'NOT YET QUEUED'},
     {'name': 'clusterCS', 'pause': 0, 'state': 'NOT YET QUEUED'},
     {'name': 'llsExportToN5', 'pause': 0, 'state': 'NOT YET QUEUED'},
     {'name': 'regiprepLabels', 'pause': 0, 'state': 'NOT YET QUEUED'},
     {'name': 'clusterFR', 'pause': 0, 'state': 'NOT YET QUEUED'},
     {'name': 'llsConvertN5ExportToSliceTIFF',
      'pause': 0,
      'state': 'NOT YET QUEUED'}]

add_fields_to_job_information_from_db_test_variables['child']['remaining_step_names'] = \
    ['clusterPT',
     'llsCreateTileConfigurationFiles',
     'c3dReformat',
     'regiprepReformat',
     'clusterMF',
     'llsConvertTilesToN5',
     'regiprepImages',
     'localAP',
     'llsFlatfieldCorrection',
     'antsRigidAffineRegistration',
     'antsDeformableRegistration',
     'clusterTF',
     'antsWarpAffine',
     'llsIgorDeconvolution',
     'localEC',
     'llsStitching',
     'antsWarpAffineAndDeformable',
     'clusterCS',
     'llsExportToN5',
     'regiprepLabels',
     'clusterFR',
     'llsConvertN5ExportToSliceTIFF']

add_fields_to_job_information_from_db_test_variables['parent'] = {}
add_fields_to_job_information_from_db_test_variables['parent']['parent_or_child'] = 'parent'
add_fields_to_job_information_from_db_test_variables['parent']['job_information_from_db_before'] = \
    [{'_id': ObjectId('5cababe94960065c9eb02488'),
      'configAddress': 'http://lightsheet:8089/config/5cababe94960065c9eb02488',
      'creationDate': '2019-04-08 16:15:37',
      'jacs_id': ['2653066155381194769'],
      'jobName': 'Job_0.35.0_2019-04-08_16:08:00_vm638.int.janelia.org',
      'remainingStepNames': ['clusterPT',
                             'llsCreateTileConfigurationFiles',
                             'c3dReformat',
                             'regiprepReformat',
                             'clusterMF',
                             'llsConvertTilesToN5',
                             'regiprepImages',
                             'localAP',
                             'llsFlatfieldCorrection',
                             'antsRigidAffineRegistration',
                             'antsDeformableRegistration',
                             'clusterTF',
                             'antsWarpAffine',
                             'llsIgorDeconvolution',
                             'localEC',
                             'llsStitching',
                             'antsWarpAffineAndDeformable',
                             'clusterCS',
                             'llsExportToN5',
                             'regiprepLabels',
                             'clusterFR',
                             'llsConvertN5ExportToSliceTIFF'],
      'state': 'ERROR',
      'steps': [{'name': 'aicSimviewSingleCameraGlobalParameters',
                 'state': 'NOT YET QUEUED'},
                {'name': 'clusterPT', 'state': 'ERROR'},
                {'name': 'llsCreateTileConfigurationFiles',
                 'state': 'NOT YET QUEUED'},
                {'name': 'c3dReformat', 'state': 'NOT YET QUEUED'},
                {'name': 'regiprepReformat', 'state': 'NOT YET QUEUED'},
                {'name': 'clusterMF', 'state': 'NOT YET QUEUED'},
                {'name': 'llsConvertTilesToN5', 'state': 'NOT YET QUEUED'},
                {'name': 'regiprepImages', 'state': 'NOT YET QUEUED'},
                {'name': 'localAP', 'state': 'NOT YET QUEUED'},
                {'name': 'llsFlatfieldCorrection', 'state': 'NOT YET QUEUED'},
                {'name': 'antsRigidAffineRegistration', 'state': 'NOT YET QUEUED'},
                {'name': 'antsDeformableRegistration', 'state': 'NOT YET QUEUED'},
                {'name': 'clusterTF', 'state': 'NOT YET QUEUED'},
                {'name': 'antsWarpAffine', 'state': 'NOT YET QUEUED'},
                {'name': 'llsIgorDeconvolution', 'state': 'NOT YET QUEUED'},
                {'name': 'localEC', 'state': 'NOT YET QUEUED'},
                {'name': 'llsStitching', 'state': 'NOT YET QUEUED'},
                {'name': 'antsWarpAffineAndDeformable', 'state': 'NOT YET QUEUED'},
                {'name': 'clusterCS', 'state': 'NOT YET QUEUED'},
                {'name': 'llsExportToN5', 'state': 'NOT YET QUEUED'},
                {'name': 'regiprepLabels', 'state': 'NOT YET QUEUED'},
                {'name': 'clusterFR', 'state': 'NOT YET QUEUED'},
                {'name': 'llsConvertN5ExportToSliceTIFF',
                 'state': 'NOT YET QUEUED'}]}]

add_fields_to_job_information_from_db_test_variables['parent']['job_information_from_db_after'] = \
    [{'_id': ObjectId('5cababe94960065c9eb02488'),
      'configAddress': 'http://lightsheet:8089/config/5cababe94960065c9eb02488',
      'creationDate': '2019-04-08 16:15:37',
      'jacs_id': ['2653066155381194769'],
      'jobName': 'Job_0.35.0_2019-04-08_16:08:00_vm638.int.janelia.org',
      'remainingStepNames': ['clusterPT',
                             'llsCreateTileConfigurationFiles',
                             'c3dReformat',
                             'regiprepReformat',
                             'clusterMF',
                             'llsConvertTilesToN5',
                             'regiprepImages',
                             'localAP',
                             'llsFlatfieldCorrection',
                             'antsRigidAffineRegistration',
                             'antsDeformableRegistration',
                             'clusterTF',
                             'antsWarpAffine',
                             'llsIgorDeconvolution',
                             'localEC',
                             'llsStitching',
                             'antsWarpAffineAndDeformable',
                             'clusterCS',
                             'llsExportToN5',
                             'regiprepLabels',
                             'clusterFR',
                             'llsConvertN5ExportToSliceTIFF'],
      'selected': '',
      'selectedStepNames': 'clusterPT,llsCreateTileConfigurationFiles,c3dReformat,regiprepReformat,clusterMF,llsConvertTilesToN5,regiprepImages,localAP,llsFlatfieldCorrection,antsRigidAffineRegistration,antsDeformableRegistration,clusterTF,antsWarpAffine,llsIgorDeconvolution,localEC,llsStitching,antsWarpAffineAndDeformable,clusterCS,llsExportToN5,regiprepLabels,clusterFR,llsConvertN5ExportToSliceTIFF',
      'state': 'ERROR',
      'steps': [{'name': 'aicSimviewSingleCameraGlobalParameters',
                 'state': 'NOT YET QUEUED'},
                {'name': 'clusterPT', 'state': 'ERROR'},
                {'name': 'llsCreateTileConfigurationFiles',
                 'state': 'NOT YET QUEUED'},
                {'name': 'c3dReformat', 'state': 'NOT YET QUEUED'},
                {'name': 'regiprepReformat', 'state': 'NOT YET QUEUED'},
                {'name': 'clusterMF', 'state': 'NOT YET QUEUED'},
                {'name': 'llsConvertTilesToN5', 'state': 'NOT YET QUEUED'},
                {'name': 'regiprepImages', 'state': 'NOT YET QUEUED'},
                {'name': 'localAP', 'state': 'NOT YET QUEUED'},
                {'name': 'llsFlatfieldCorrection', 'state': 'NOT YET QUEUED'},
                {'name': 'antsRigidAffineRegistration', 'state': 'NOT YET QUEUED'},
                {'name': 'antsDeformableRegistration', 'state': 'NOT YET QUEUED'},
                {'name': 'clusterTF', 'state': 'NOT YET QUEUED'},
                {'name': 'antsWarpAffine', 'state': 'NOT YET QUEUED'},
                {'name': 'llsIgorDeconvolution', 'state': 'NOT YET QUEUED'},
                {'name': 'localEC', 'state': 'NOT YET QUEUED'},
                {'name': 'llsStitching', 'state': 'NOT YET QUEUED'},
                {'name': 'antsWarpAffineAndDeformable', 'state': 'NOT YET QUEUED'},
                {'name': 'clusterCS', 'state': 'NOT YET QUEUED'},
                {'name': 'llsExportToN5', 'state': 'NOT YET QUEUED'},
                {'name': 'regiprepLabels', 'state': 'NOT YET QUEUED'},
                {'name': 'clusterFR', 'state': 'NOT YET QUEUED'},
                {'name': 'llsConvertN5ExportToSliceTIFF',
                 'state': 'NOT YET QUEUED'}]}]
